name: 'Plagiarism Report'
on:
  workflow_run:
    workflows: [ 'CI' ]                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DmitryAlexandrovv/plagiarism-action@master
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
